name: Deploy Review App
on:
  # Run this workflow on every PR event. Existing review apps will be updated when the PR is updated.
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  # Set these to your Fly.io organization and preferred region.
  FLY_REGION: iad
  FLY_ORG: personal

jobs:
  review_app:
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    # Only run one deployment at a time per PR.
    concurrency:
      group: pr-${{ github.event.number }}

    # Deploying apps with this "review" environment allows the URL for the app to be displayed in the PR UI.
    # Feel free to change the name of this environment.
    environment:
      name: pr-${{ github.event.number }}
      # The script in the `deploy` sets the URL output for each review app.
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Deploy PR app to Fly.io
        id: deploy
        uses: superfly/fly-pr-review-apps@1.2.0
        with:
          secrets: SUPABASE_URL=${{secrets.SUPABASE_URL}} SUPABASE_ANON_KEY=${{secrets.SUPABASE_ANON_KEY}}
      
      - name: Get GH App token
        uses: actions/create-github-app-token@v1
        if: ${{ github.event.action == 'closed' }}
        id: get-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      # - name: 🗑 Delete deployment environment
      #   uses: strumwolf/delete-deployment-environment@v2.2.3
      #   if: ${{ github.event.action == 'closed' }}
      #   with:
      #     token: ${{ steps.get-token.outputs.token }}
      #     environment: pr-${{ github.event.number }}
      #     ref: ${{ github.ref_name }}

      - name: Clean up GitHub environment
        if: ${{ github.event.action == 'closed' }}
        run: |
          curl -v -X DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ steps.get-token.outputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/anniebabannie/design-timeline/environments/pr-${{ github.event.number }}"
